sudo: required
services:
  - docker

before_install:
  - docker build -t alexeysumin94/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexeysumin94/docker-react npm run test -- --coverage